# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwarder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='auth_password',
            field=models.CharField(default='invalid', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='auth_username',
            field=models.CharField(default='invalid', max_length=128),
            preserve_default=False,
        ),
    ]
